name: remote_pull

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  remote_pull:
    runs-on: ubuntu-latest
    steps:
      - name: connect to ssh and git pull
        run: |
          KEY="${{ secrets.SSH_PRIVATE_KEY }}"
          echo "${KEY}" | grep -qw "less" | ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} 'cd ${{ secrets.FILE_PATH }} && git pull'
